### ISSUE TITLE
Python/Django?

### ISSUE THREAD

**Issue by nipython** [strizhechenko/strizhechenko.github.io#1]
Здравствуйте, Олег!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python от 2-х лет до 100 лет (а опыт с Python-ом у вас есть, судя по репозиторию :), пониманием веба, опытом в Django, возможностью разговаривать хотя бы на ломаном английском :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас И вам было бы интересно переехать в Минск работать в штате компании на лучших условиях (удаленно мы не можем, увы).
Спасибо

**Comment by strizhechenko** [comment]
Добрый день. 

Вряд ли я вам подойду, это предложение звучит так, будто вы даже [резюме](https://strizhechenko.github.io/en/ru_resume.html) не читали. Можете попробовать высчитать сколько надо платить, чтобы [заманить меня](https://docs.google.com/spreadsheets/d/1PvVZqetoa2ntvmK8Rh_GwTsQnVdwaiEycB6VfNb3ezQ/edit?usp=sharing), с учётом того что django я не знаю и оно мне не особо интересно.
